# .github/workflows/ci.yml

name: CI Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: set-up python 3.9
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    # - uses: iterative/setup-cml@v2
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#  pip install -r requirements.txt
    
    # - name: Run main file
    #   run: |
    #     python main.py
    
    - name: Test with pytest
      run: |
        pytest -v

    # - name: Run Tests
    #   run: |
    #     python -m unittest discover

    # - name: Create CML report
    #   env:
    #     REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |

    #     echo "# First Line of our report" >> report.md
    #     echo "## Bar Plots" >> report.md
    #     echo '![](./bars.png "Bar plot")' >> report.md
    #     echo "## Line Plots" >> report.md
    #     echo '![](./lines.png "Bar plot")' >> report.md

    #     cml comment create report.md